# Generated by Django 3.0.3 on 2020-02-18 17:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.CharField(default=datetime.datetime(2020, 2, 18, 17, 17, 14, 166700, tzinfo=utc), max_length=400),
            preserve_default=False,
        ),
    ]
