# Generated by Django 3.0.3 on 2020-02-18 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200218_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 2, 18, 18, 28, 57, 205363, tzinfo=utc), max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
