# Generated by Django 3.0.3 on 2020-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200219_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30, verbose_name='Класс')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(upload_to='timetable/%Y/%m/', verbose_name='Картинка')),
            ],
        ),
    ]
