# Generated by Django 3.0.3 on 2020-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('place', models.CharField(max_length=300, verbose_name='Должность')),
                ('cover', models.ImageField(upload_to='teachers/%Y/%m', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписании'},
        ),
        migrations.AlterField(
            model_name='timetable',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='ID'),
        ),
    ]
