# Generated by Django 3.0.3 on 2020-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200223_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('medalist', models.CharField(max_length=600, verbose_name='Достижении')),
                ('cover', models.ImageField(upload_to='awards/%Y/%m', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Призёр',
                'verbose_name_plural': 'Призёры',
            },
        ),
    ]
