# Generated by Django 3.0.3 on 2020-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_awards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-id', '-publish'), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='awards',
            name='medalist_en',
            field=models.CharField(max_length=600, null=True, verbose_name='Достижении'),
        ),
        migrations.AddField(
            model_name='awards',
            name='medalist_kk',
            field=models.CharField(max_length=600, null=True, verbose_name='Достижении'),
        ),
        migrations.AddField(
            model_name='awards',
            name='medalist_ru',
            field=models.CharField(max_length=600, null=True, verbose_name='Достижении'),
        ),
        migrations.AddField(
            model_name='awards',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='awards',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='awards',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions_kk',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='place_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='place_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='place_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность'),
        ),
    ]
